spring:
  application:
    name: microbank-customer-service
  data:
    mongodb:
      database: microbank
server:
  servlet:
    context-path: /microbank
---
server:
  port: 9010
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka