spring:
  application:
    name: microbank-customer-service
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create-drop
  datasource:
    url: jdbc:h2:file:~/data/microbank/customer-database
    username: sa
    password: 
    driver-class-name: org.h2.Driver
---
server:
  port: 9010
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka