spring:
  application:
    name: microbank-customer-service
server:
  servlet:
    context-path: /microbank-customer
---
server:
  port: 6010
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
customer:
  mongodb:
    host: freecluster-s3rjf.mongodb.net
    user: AtlasAdmin
    db: microbank