version: "3"
services:
  microbank-eureka-server:
    image: microbank-eureka:latest
    ports:
      - "8761:8761"
  microbank-zuul-gateway:
    image: microbank-zuul:latest
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://microbank-eureka-server:8761/eureka
  microbank-registration:
    image: microbank-registration:latest
    ports:
      - "9010:9010"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://microbank-eureka-server:8761/eureka
