spring:
  application:
    name: microbank-zuul-gateway
---
server:
  port: 8765
---
zuul:
  retryable: true
  routes:
    customer:
      service-id: microbank-customer-service
---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka