spring:
  application:
    name: microbank-zuul-gateway
---
server:
  port: 8765
---
zuul:
  retryable: true
---
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka